version: '3.8'

services:
  mongo-db:
    image: mongo:6.0-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  # postgres-db:
  #   image: postgres:15.3
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_HOST}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432